---
- name: Install Apps
  win_chocolatey:
    name:
      - ghidra
      - 010editor
      - die
      - explorersuite
      - dnspy
      - ilspy
      - sysinternals
      - fiddler
      - x64dbg
      - ida-free
    state: present
    ignore_checksums: true
