---
- name: Add Fireeye chocolatey repo
  win_chocolatey_source:
    name: fireeye
    state: present
    source: https://www.myget.org/F/fireeye/api/v2
- name: Install Apps
  win_chocolatey:
    name:
      - ghidra
      - 010editor
      - die
      - explorersuite
      - dnspy
      - ilspy
      - sysinternals
      - fiddler
      - x64dbg
      - ida-free
      - radare2
      - openjdk
      - microsoft-build-tools
    state: present
    ignore_checksums: true
