---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  inventory:
    group_vars:
      windows:
        ansible_become: false
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_shell_type: cmd
verifier:
  name: ansible