---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: win10-molecule
    box: win10_1904_nosysprep
    box_url: https://pentesterwtf.s3-ap-southeast-2.amazonaws.com/vagrant/windows-10-1904-nosysprep.box
    groups:
      - windows
  - name: win2019-molecule
    box: win2019_nosysprep
    box_url: https://pentesterwtf.s3-ap-southeast-2.amazonaws.com/vagrant/windows_server_2019-nosysprep.box
    groups:
      - windows
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  inventory:
    group_vars:
      windows:
        ansible_become: false
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_shell_type: cmd
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint roles/*
  #yamllint .