---
# This is a workaround for the upstream chocolately package
# Which isn't updated to latest hash

- name: Download sysmon
  win_get_url:
    url: https://download.sysinternals.com/files/Sysmon.zip
    dest: C:\sysmon.zip
  register: downloaded

- name: Unzip a bz2 (BZip) file
  win_unzip:
    src: C:\sysmon.zip
    dest: C:\windows\system32\
    creates: C:\Users\Phil\OldLogs
  when: downloaded.changed

- name: Get SwiftOnSecurity sysmon config
  win_get_url:
    url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
    dest: C:\windows\sysmonconfig-export.xml

- name: Configure sysmon
  win_command: powershell.exe -
  args:
    stdin: C:\windows\system32\sysmon.exe -accepteula -i C:\windows\sysmonconfig-export.xml
