---
name: Molecule testing
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo ANSIBLE_SKIP_CONFLICT_CHECK=1 python3 -m pip install "molecule[lint]"
          sudo ANSIBLE_SKIP_CONFLICT_CHECK=1 python3 -m pip install "molecule-vagrant"
      - name: Lint with Molecule
        run: |
          molecule lint