---
name: Molecule testing
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install podman -y
          sudo apt-get remove ansible -y
          sudo python3 -m pip install "molecule[lint,ansible,ansible-base]"
      - name: Lint with Molecule
        run: |
          molecule lint
  end-to-end:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
      - name: Install/Enable Winrm
        shell: powershell
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
          net user /add vagrant Vagrant123!
          net localgroup administrators vagrant /add
          Start-Service sshd
          Set-Service -Name sshd -StartupType 'Automatic'
          Get-NetFirewallRule -Name *ssh*
          New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
      - name: test
        shell: powershell
        run: netstat -ano
      - name: Install dependencies
        shell: wsl-bash {0}
        run: |
          apt-get update -y
          apt install python3 python3-pip -y
          python3 -m pip install "molecule[lint,ansible,ansible-base]"
          python3 -m pip install "pywinrm"
          ansible-galaxy collection install ansible.windows
          ansible-galaxy collection install community.windows
          ansible-galaxy collection install chocolatey.chocolatey
      - name: Run end-to-end test with molecule
        shell: wsl-bash {0}
        run: |
          molecule test
